# Generated by Django 2.1.2 on 2018-10-27 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='csvFile',
        ),
        migrations.AddField(
            model_name='document',
            name='username',
            field=models.CharField(default='', max_length=200),
        ),
    ]
